/**
 * Even Fibonacci numbers
 * Problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 */
public class sol {
	public static void main(String[] args) {
		int fib1 = 0, fib2 = 0, result = 0;
		
		for (int num2 = 0, num1 = 1; num1 < 4000000 || num2 < 4000000; num2 += num1) {
			num1 += num2;
			fib1 = num2 % 2;
			fib2 = num1 % 2;
			if (fib1 == 0) {
				result += num2;
			} else if (fib2 == 0) {
				result += num1;
			}
		}

		System.out.println(result);
	}
}
